apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo1-c066"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo1-c066"
  template:
    metadata:
      labels:
        app: "aksdemo1-c066"
    spec:
      containers:
        - name: "aksdemo1-c066"
          image: "akscicdacr.azurecr.io/aksdemo1"
          ports:
          - containerPort: 80